# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170721_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='id',
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(default='tool', max_length=200),
        ),
    ]
