# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 05:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20170722_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 7, 25, 5, 18, 50, 588766))),
                ('status', models.IntegerField(default=1)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
